name: Probar Token
on: 
  push:
  workflow_dispatch:

jobs:
  verificar-token:
    runs-on: self-hosted
    steps:
      - name: Comparar tokens
        run: |
          if [ "${{ secrets.DEV_TOKEN }}" = "111111" ]; then
            echo "Los tokens coinciden (Correcto)"
          else
            echo "Los tokens NO coinciden (Error)"
            exit 1
          fi